# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1

jobs:
  build:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build -t ${AWS_ECR_ACCOUNT_URL}/go-demo-app:123 .

workflows:
  build_and_push:
    jobs:
      - build:
          name: build_image
      - aws-ecr/build-and-push-image:
          requires: ["build_image"]
          name: push_to_ecr
          repo: "go-demo-app"
          tag:  "123"
