version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1

jobs:
  build:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build -t ${AWS_ECR_ACCOUNT_URL}/go-demo-app:123 .
  hello:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

workflows:
  build_and_push:
    jobs:
      - build:
          name: build_image
      - aws-ecr/build-and-push-image:
          requires: ["build_image"]
          name: push_to_ecr
          repo: "go-demo-app"
          tag:  "123"
  hello_world:
    jobs:
      - hello
